return {
  ball = {
    x = 150,
    y = 460,
  },
  obstacles = {
    {
      type = "corner",
      x = 0,
      y = 380,
      width = 80,
      height = 80,
    },
    {
      type = "corner",
      x = 220,
      y = 380,
      width = 80,
      height = 80,
      rotation = 270,
    },
    {
      type = "corner",
      x = 220,
      y = 0,
      width = 80,
      height = 80,
      rotation = 180,
    },
    {
      type = "horizontal-barrier",
      x = 0,
      y = 300,
      width = 80,
      height = 30,
    },
    {
      type = "horizontal-barrier-large",
      x = 40,
      y = 220,
      width = 140,
      height = 30,
    },
    {
      type = "horizontal-barrier-large",
      x = 55,
      y = 90,
      width = 200,
      height = 30,
    },
    {
      type = "vertical-barrier",
      x = 230,
      y = 200,
      width = 30,
      height = 150,
    },
  },
  stars = {
    one = 6,
    two = 4,
    three = 2,
  },
  targets = {
    {
      type = "easy",
      x = 60,
      y = 40,
      width = 40,
      height = 40,
    },
    {
      type = "normal",
      x = 220,
      y = 140,
      width = 40,
      height = 40,
    },
    {
      type = "hard",
      x = 60,
      y = 170,
      width = 40,
      height = 40,
    },
  },
}
